// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebClinic.Models;

namespace WebClinic.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190625165320_CustoCorrecao001")]
    partial class CustoCorrecao001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebClinic.Models.Animal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Especie");

                    b.Property<string>("Nome");

                    b.Property<int>("ProprietarioID");

                    b.Property<string>("Raca");

                    b.Property<string>("Sexo");

                    b.HasKey("ID");

                    b.HasIndex("ProprietarioID");

                    b.ToTable("Animal");
                });

            modelBuilder.Entity("WebClinic.Models.Medico", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CRMV");

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Nome");

                    b.Property<string>("Sobrenome");

                    b.HasKey("ID");

                    b.ToTable("Medico");
                });

            modelBuilder.Entity("WebClinic.Models.Procedimento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnimalID");

                    b.Property<DateTime>("DataRealizacao");

                    b.Property<int>("MedicoID");

                    b.Property<int>("TipoProcedimentoID");

                    b.HasKey("ID");

                    b.HasIndex("AnimalID");

                    b.HasIndex("MedicoID");

                    b.HasIndex("TipoProcedimentoID");

                    b.ToTable("Procedimento");
                });

            modelBuilder.Entity("WebClinic.Models.Proprietario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Nome");

                    b.Property<string>("Sobrenome");

                    b.HasKey("ID");

                    b.ToTable("Proprietario");
                });

            modelBuilder.Entity("WebClinic.Models.TipoProcedimento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Custo")
                        .HasColumnType("money");

                    b.Property<string>("Descricao");

                    b.Property<string>("Nome");

                    b.HasKey("ID");

                    b.ToTable("TipoProcedimento");
                });

            modelBuilder.Entity("WebClinic.Models.Animal", b =>
                {
                    b.HasOne("WebClinic.Models.Proprietario", "Proprietario")
                        .WithMany("Animais")
                        .HasForeignKey("ProprietarioID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebClinic.Models.Procedimento", b =>
                {
                    b.HasOne("WebClinic.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebClinic.Models.Medico", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebClinic.Models.TipoProcedimento", "TipoProcedimento")
                        .WithMany()
                        .HasForeignKey("TipoProcedimentoID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
